### set mission to in-progress
# @prompt mission_id Mission ID to Set In-Progress
PATCH  {{base_url}}/mission/in-progress/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### set mission to completed
# @prompt mission_id Mission ID to Set Completed
PATCH  {{base_url}}/mission/to-completed/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### set mission to failed
# @prompt mission_id Mission ID to Set Failed
PATCH  {{base_url}}/mission/to-failed/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
